version: '3.8'
services:
  database:
    image: postgres:13
    container_name: wallet_db
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db_data:
